# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsuser',
            name='portrait',
            field=models.ImageField(upload_to='./user/portrait/%Y/%m/%d', verbose_name='\u7528\u6237\u5934\u50cf\u8def\u5f84'),
        ),
    ]
